(function (window, document) {
    'use strict';
    const config = window.DELIVERY_MANAGEMENT || {};
    let workers = [], plans = [], zones = [], settlements = [], currentPreview = null;
    const q = function (selector, root) { return (root || document).querySelector(selector); };
    const qa = function (selector, root) { return Array.from((root || document).querySelectorAll(selector)); };
    function esc(value) { const d = document.createElement('div'); d.textContent = value == null ? '' : String(value); return d.innerHTML; }
    function money(value) { return Number(value || 0).toFixed(3); }
    function friendlyError(message) { const labels={DELIVERY_SCHEMA_MIGRATIONS_PENDING:'يلزم تطبيق تحديثات قاعدة بيانات التوصيل قبل استخدام هذه الوظيفة.',CSRF_INVALID:'انتهت صلاحية جلسة العمل. حدّث الصفحة ثم حاول مرة أخرى.',DELIVERY_PLAN_VERSION_LOCKED:'هذه الخطة استُخدمت في طلبات سابقة. أنشئ خطة جديدة للحفاظ على التاريخ المالي.',DELIVERY_PLAN_BASE_PERIOD_INVALID:'نوع الأجر الأساسي غير صحيح.',DELIVERY_PLAN_METHOD_INVALID:'طريقة حساب مستحق الطلب غير صحيحة.',DELIVERY_PLAN_TIPS_MODE_INVALID:'طريقة احتساب الإكرامية غير صحيحة.',DELIVERY_SETTLEMENT_PERIOD_OVERLAP:'توجد تسوية معتمدة للعامل تتداخل مع هذه الفترة.',DELIVERY_SETTLEMENT_FUND_REQUIRED:'اختر حساب الصندوق أو البنك لإتمام التسوية.',DELIVERY_SETTLEMENT_OPEN_DRAWER_REQUIRED:'التسوية النقدية تحتاج إلى درج نقدي مفتوح.',DELIVERY_SETTLEMENT_OFFSET_REQUIRES_ZERO_NET:'المقاصة فقط متاحة عندما يكون صافي التسوية صفراً.',DELIVERY_DEDUCTIONS_EXCEED_EARNINGS:'الخصومات لا يمكن أن تتجاوز مستحقات العامل.',DELIVERY_SETTLEMENT_EMPTY:'لا توجد مبالغ قابلة للتسوية في هذه الفترة.',DELIVERY_SETTLEMENT_REVERSAL_REASON_REQUIRED:'اكتب سبباً واضحاً لعكس التسوية.',DELIVERY_ORDER_NOT_FOUND:'طلب التوصيل غير موجود في هذا الفرع.',DELIVERY_WORKER_UNAVAILABLE:'عامل التوصيل غير متاح حالياً.'};return labels[message]||message||'تعذر إتمام العملية'; }
    function error(message) { const box = q('#deliveryManagementAlert'); if (!box) return; box.textContent = friendlyError(message); box.classList.remove('d-none'); window.scrollTo({ top: 0, behavior: 'smooth' }); }
    async function request(url, options) { const response = await fetch(url, Object.assign({ headers: { Accept: 'application/json', 'X-Requested-With': 'XMLHttpRequest' } }, options || {})); const body = await response.json().catch(function () { return {}; }); if (!response.ok || !body.success) throw new Error(body.code || body.error || body.message || 'تعذر إتمام الطلب'); return body; }
    function post(url, data) { data.csrf_token = config.csrf; return request(url, { method: 'POST', body: new URLSearchParams(data) }); }
    function formData(form) { return Object.fromEntries(new FormData(form).entries()); }
    function methodLabel(plan) { const labels = { customer_fee: 'رسوم العميل', fixed: 'ثابت ' + money(plan.per_delivery_value), percentage: money(plan.per_delivery_value) + '%', zone_rate: 'حسب المنطقة', none: 'بدون' }; return labels[plan.per_delivery_method] || plan.per_delivery_method; }
    function financialPosition(value, overview) {
        const net = Number(value || 0);
        if (net < -0.0005) return { kind: 'shop', label: overview ? 'مبالغ يجب أن يوردها العمال للمحل' : 'على العامل توريده للمحل', amount: Math.abs(net) };
        if (net > 0.0005) return { kind: 'worker', label: overview ? 'مستحقات يجب أن يدفعها المحل للعمال' : 'للعامل لدى المحل', amount: net };
        return { kind: 'balanced', label: overview ? 'لا توجد مبالغ مفتوحة للتسوية' : 'الحساب متوازن', amount: 0 };
    }
    function settlementPosition(settlement) {
        const direction = settlement.settlement_direction || '';
        if (direction === 'worker_pays') return { kind: 'shop', label: 'وردها العامل للمحل', amount: Math.abs(Number(settlement.net_amount || 0)) };
        if (direction === 'shop_pays') return { kind: 'worker', label: 'دفعها المحل للعامل', amount: Math.abs(Number(settlement.net_amount || 0)) };
        return financialPosition(settlement.net_amount, false);
    }
    function workerDues(worker) {
        const workerEarnings = Number(worker.open_delivery_earnings || 0) + Number(worker.open_tips || 0);
        return '<div class="delivery-balance delivery-balance--worker"><strong>'+money(workerEarnings)+' ج.م</strong></div>';
    }
    function syncBaseAmountField() {
        const period = q('#deliveryPlanForm [name="base_period"]');
        const amount = q('#deliveryPlanForm [name="base_amount"]');
        if (!period || !amount) return;
        const hasBasePay = period.value !== 'none';
        amount.disabled = !hasBasePay;
        if (!hasBasePay) amount.value = '0';
    }
    function settlementStatus(value) { return value === 'reversed' ? 'معكوسة' : 'معتمدة'; }
    function paymentMethod(value) { return ({cash:'نقدي',bank:'بنكي',offset:'مقاصة'})[value] || value; }
    function render() {
        const active = workers.filter(function (w) { return Number(w.is_active) === 1; });
        const activeOrders = workers.reduce(function (s, w) { return s + Number(w.active_orders || 0); }, 0);
        const openMoney = workers.reduce(function (s, w) { return s + Number(w.open_net_amount || 0); }, 0);
        const overviewPosition = financialPosition(openMoney, true);
        const kpis = q('#deliveryKpis'); if (kpis) kpis.innerHTML = [['عمال نشطون',active.length],['طلبات مع العمال',activeOrders],['خطط نشطة',plans.filter(function(p){return Number(p.is_active)===1;}).length]].map(function (x) { return '<div class="delivery-kpi"><span>'+esc(x[0])+'</span><strong>'+esc(x[1])+'</strong></div>'; }).join('')+'<div class="delivery-kpi delivery-kpi--financial delivery-kpi--'+overviewPosition.kind+'"><span>'+esc(overviewPosition.label)+'</span><strong>'+money(overviewPosition.amount)+' ج.م</strong><small>بعد احتساب أموال الطلبات ومستحقات العمال</small></div>';
        const workerPlan = q('#workerPlanSelect'); if (workerPlan) workerPlan.innerHTML = '<option value="">بدون خطة</option>' + plans.filter(function(p){return Number(p.is_active)===1;}).map(function(p){return '<option value="'+p.id+'">'+esc(p.name)+'</option>';}).join('');
        const settlementWorker = q('#settlementWorkerSelect'); if (settlementWorker) settlementWorker.innerHTML = '<option value="">اختر العامل</option>' + active.map(function(w){return '<option value="'+w.id+'">'+esc(w.name)+'</option>';}).join('');
        const wt = q('#deliveryWorkersTable'); if (wt) wt.innerHTML = workers.map(function(w){const failedCount=Number(w.failed_order_count||0);const failed=failedCount?'<strong class="text-danger">'+failedCount+'</strong><br><small>قيمة الطلبات '+money(w.failed_order_value)+' ج.م · نقدية غير مؤكدة '+money(w.failed_cod_exposure)+' ج.م</small>':'0';return '<tr><td><strong>'+esc(w.name)+'</strong><br><small>'+esc(w.phone||'')+'</small></td><td>'+esc(w.compensation_plan_name||'بدون خطة')+'</td><td>'+Number(w.active_orders||0)+'</td><td>'+failed+'</td><td>'+workerDues(w)+'</td><td>'+(Number(w.is_active)?(Number(w.is_available)?'متاح':'غير متاح'):'موقوف')+'</td><td><button class="delivery-button worker-edit" data-id="'+w.id+'">تعديل</button></td></tr>';}).join('') || '<tr><td colspan="7">لا يوجد عمال بعد</td></tr>';
        const pt = q('#deliveryPlansTable'); if (pt) pt.innerHTML = plans.map(function(p){return '<tr><td><strong>'+esc(p.name)+'</strong></td><td>'+esc(p.base_period==='none'?'بدون':money(p.base_amount)+' / '+p.base_period)+'</td><td>'+esc(methodLabel(p))+'</td><td>'+esc(p.effective_from)+'</td><td><button class="delivery-button plan-edit" data-id="'+p.id+'">تعديل</button></td></tr>';}).join('') || '<tr><td colspan="5">لا توجد خطط بعد</td></tr>';
        const st = q('#deliverySettlementsTable'); if (st) st.innerHTML = settlements.map(function(s){const position=settlementPosition(s);const reverse=config.canReverse&&s.status==='finalized'?'<button class="delivery-button settlement-reverse" data-id="'+s.id+'">عكس</button>':'';return '<tr><td>'+esc(s.worker_name||'')+'</td><td>'+esc(s.period_start)+' — '+esc(s.period_end)+'</td><td>'+esc(s.delivery_earnings)+'</td><td><strong>'+money(position.amount)+' ج.م</strong><br><small>'+esc(position.label)+' · '+esc(settlementStatus(s.status))+'</small></td><td>'+esc(paymentMethod(s.payment_method))+' '+reverse+'</td></tr>';}).join('') || '<tr><td colspan="5">لا توجد تسويات بعد</td></tr>';
        const recent = q('#deliveryRecentSettlements'); if (recent) recent.innerHTML = settlements.slice(0,6).map(function(s){const position=settlementPosition(s);return '<tr><td>'+esc(s.worker_name||'')+'</td><td>'+esc(s.period_start)+' — '+esc(s.period_end)+'</td><td><strong>'+money(position.amount)+' ج.م</strong><br><small>'+esc(position.label)+'</small></td><td>'+esc(settlementStatus(s.status))+'</td></tr>';}).join('') || '<tr><td colspan="4">لا توجد تسويات بعد</td></tr>';
        renderZoneRates();
    }
    function renderZoneRates(values) { const root=q('#deliveryZoneRates'); const method=q('#deliveryPlanForm [name="per_delivery_method"]'); if(!root||!method){return;} if(method.value!=='zone_rate'){root.innerHTML='';return;} values=values||{}; root.innerHTML='<strong>مبلغ العامل حسب المنطقة</strong><div class="delivery-form-grid mt-2">'+zones.map(function(z){return '<label>'+esc(z.name)+'<input class="zone-rate-input" data-zone-id="'+z.id+'" type="number" min="0" step="0.001" value="'+esc(values[z.id]||0)+'"></label>';}).join('')+'</div>'; }
    async function load() { try { const calls=[request('ajax/delivery_workers.php?include_inactive=1'),request('ajax/delivery_plans.php?include_inactive=1'),request('ajax/delivery_zones_list.php')]; if(config.canSettlements) calls.push(request('ajax/delivery_settlements.php')); const data=await Promise.all(calls); workers=data[0].workers||[]; plans=data[1].plans||[]; zones=data[2].zones||[]; settlements=data[3]?data[3].settlements||[]:[]; render(); } catch(e){error(e.message);} }
    qa('.delivery-tab').forEach(function(tab){tab.addEventListener('click',function(){qa('.delivery-tab').forEach(function(x){x.classList.remove('is-active');});qa('.delivery-panel').forEach(function(x){x.classList.remove('is-active');});tab.classList.add('is-active');const panel=q('[data-panel="'+tab.dataset.tab+'"]');if(panel)panel.classList.add('is-active');});});
    const workerForm=q('#deliveryWorkerForm'); if(workerForm) workerForm.addEventListener('submit',async function(e){e.preventDefault();try{await post('ajax/delivery_workers.php',formData(workerForm));workerForm.reset();q('[name="id"]',workerForm).value='0';await load();}catch(ex){error(ex.message);}});
    const planForm=q('#deliveryPlanForm'); if(planForm){q('[name="base_period"]',planForm).addEventListener('change',syncBaseAmountField);q('[name="per_delivery_method"]',planForm).addEventListener('change',function(){renderZoneRates();});planForm.addEventListener('submit',async function(e){e.preventDefault();const data=formData(planForm);const rates={};qa('.zone-rate-input',planForm).forEach(function(input){rates[input.dataset.zoneId]=input.value;});data.zone_rates_json=JSON.stringify(rates);try{await post('ajax/delivery_plans.php',data);planForm.reset();q('[name="id"]',planForm).value='0';syncBaseAmountField();await load();}catch(ex){error(ex.message);}});syncBaseAmountField();}
    document.addEventListener('click',async function(e){const wb=e.target.closest('.worker-edit');if(wb&&workerForm){const w=workers.find(function(x){return Number(x.id)===Number(wb.dataset.id);});if(!w)return;Object.keys(w).forEach(function(k){const f=q('[name="'+k+'"]',workerForm);if(f)f.value=w[k]==null?'':w[k];});workerForm.scrollIntoView({behavior:'smooth'});}const pb=e.target.closest('.plan-edit');if(pb&&planForm){const p=plans.find(function(x){return Number(x.id)===Number(pb.dataset.id);});if(!p)return;Object.keys(p).forEach(function(k){const f=q('[name="'+k+'"]',planForm);if(f)f.value=p[k]==null?'':p[k];});syncBaseAmountField();const rates={};(p.zone_rates||[]).forEach(function(r){rates[r.zone_id]=r.amount;});renderZoneRates(rates);planForm.scrollIntoView({behavior:'smooth'});}const rb=e.target.closest('.settlement-reverse');if(rb){const reason=window.prompt('سبب عكس التسوية');if(!reason)return;try{await post('ajax/delivery_settlements.php',{action:'reverse',settlement_id:rb.dataset.id,reason:reason,drawer_session_id:config.drawerSessionId||0});await load();}catch(ex){error(ex.message);}}});
    async function preview(){const form=q('#deliverySettlementForm');const data=formData(form);data.action='preview';try{const result=await post('ajax/delivery_settlements.php',data);currentPreview=result.settlement;const p=currentPreview;const position=settlementPosition(p);q('#deliverySettlementPreview').innerHTML='<h3>ملخص قبل الاعتماد</h3><div class="delivery-kpis"><div class="delivery-kpi"><span>الطلبات</span><strong>'+p.order_count+'</strong></div><div class="delivery-kpi"><span>إجمالي مستحقات العامل</span><strong>'+money(Number(p.delivery_earnings)+Number(p.base_pay)+Number(p.tips)+Number(p.bonuses))+' ج.م</strong></div><div class="delivery-kpi"><span>استلمها العامل من العملاء</span><strong>'+money(p.cod_held)+' ج.م</strong></div><div class="delivery-kpi delivery-kpi--financial delivery-kpi--'+position.kind+'"><span>'+esc(position.label)+'</span><strong>'+money(position.amount)+' ج.م</strong></div></div><p class="delivery-settlement-explainer">النتيجة محسوبة بعد خصم الأموال التي استلمها العامل من العملاء من مستحقاته.</p>';q('#deliveryFinalizeSettlement').disabled=false;}catch(ex){error(ex.message);}}
    const previewButton=q('#deliveryPreviewSettlement');if(previewButton)previewButton.addEventListener('click',preview);const finalizeButton=q('#deliveryFinalizeSettlement');if(finalizeButton)finalizeButton.addEventListener('click',async function(){if(!currentPreview||!window.confirm('اعتماد التسوية؟ لا يمكن تعديلها بعد الاعتماد.'))return;const form=q('#deliverySettlementForm');const data=formData(form);data.action='finalize';data.idempotency_key='delivery-settlement:'+data.worker_id+':'+data.period_start+':'+data.period_end+':'+Date.now();try{await post('ajax/delivery_settlements.php',data);currentPreview=null;finalizeButton.disabled=true;q('#deliverySettlementPreview').innerHTML='<p class="text-success mb-0">تم اعتماد التسوية وتسجيل القيد المالي.</p>';await load();}catch(ex){error(ex.message);}});
    document.addEventListener('DOMContentLoaded',load);
})(window, document);
