<?php
declare(strict_types=1);
require_once __DIR__.'/../../classes/Sync/SchemaManager.php';
require_once __DIR__.'/../../classes/Sync/BranchIdentity.php';
require_once __DIR__.'/../../classes/Sync/OperationalSyncEventService.php';
require_once __DIR__.'/../../classes/Sync/PurchaseOrderSyncPayloadService.php';
require_once __DIR__.'/../../classes/Sync/CloudOperationalMirrorService.php';
require_once __DIR__.'/../../classes/Sync/SyncApplyMode.php';
require_once __DIR__.'/../../classes/Sync/SyncInboxService.php';
require_once __DIR__.'/../../classes/Sync/RestoreEventPhase.php';
mysqli_report(MYSQLI_REPORT_ERROR|MYSQLI_REPORT_STRICT);
$host=getenv('POSMAIN_TEST_MYSQL_HOST')?:'127.0.0.1';$port=(int)(getenv('POSMAIN_TEST_MYSQL_PORT')?:3307);$user=getenv('POSMAIN_TEST_MYSQL_USER')?:'root';$pass=getenv('POSMAIN_TEST_MYSQL_PASS')?:'';
$admin=new mysqli($host,$user,$pass,'',$port);$sourceDb='po_restore_source_'.getmypid();$targetDb='po_restore_target_'.getmypid();$source=$target=null;
try{
 foreach([$sourceDb,$targetDb] as $db)$admin->query("CREATE DATABASE `{$db}` CHARACTER SET utf8mb4");
 $source=new mysqli($host,$user,$pass,$sourceDb,$port);$target=new mysqli($host,$user,$pass,$targetDb,$port);foreach([$source,$target] as $c)(new SyncSchemaManager())->apply($c);
 $branch='91919191-9191-4191-8191-919191919191';$uuid='92929292-9292-4292-8292-929292929292';
 $stmt=$source->prepare("INSERT INTO inventory_purchase_orders(id,purchase_order_uuid,pos_tenant,pos_branch,branch_uuid,supplier_account_id,destination_store_id,status,expected_at,created_by,submitted_by,approved_by,created_at,submitted_at,approved_at,updated_at,notes,sync_revision) VALUES(91,?,1,2,?,44,5,'partially_received','2026-07-20 09:00:00',7,8,9,'2026-07-16 09:00:00','2026-07-16 09:10:00','2026-07-16 09:20:00','2026-07-16 10:00:00','Weekly order',4)");$stmt->bind_param('ss',$uuid,$branch);$stmt->execute();$stmt->close();
 $source->query("INSERT INTO inventory_purchase_order_lines(id,purchase_order_id,item_id,ordered_qty,received_qty,unit_cost,total_cost,created_at,updated_at) VALUES(911,91,501,'10.000000','4.000000','3.000000','30.000000','2026-07-16 09:00:00','2026-07-16 10:00:00'),(912,91,502,'6.000000','2.000000','2.000000','12.000000','2026-07-16 09:00:00','2026-07-16 10:00:00')");
 $config=['role'=>'branch','branch'=>['uuid'=>$branch,'name'=>'PO Restore','pos_tenant'=>1,'pos_branch'=>2],'sync'=>['outbox_enabled'=>true,'branch_sync_enabled'=>true,'operational_sync_enabled'=>true]];(new SyncBranchIdentity())->ensure($source,$config);(new OperationalSyncEventService())->recordPurchaseOrderSnapshot($source,91,['config'=>$config]);
 $row=$source->query("SELECT * FROM sync_outbox WHERE aggregate_type='purchase_order' AND aggregate_local_id=91")->fetch_assoc();$event=['event_uuid'=>$row['event_uuid'],'idempotency_key'=>$row['idempotency_key'],'aggregate_type'=>$row['aggregate_type'],'aggregate_uuid'=>$row['aggregate_uuid'],'aggregate_local_id'=>(int)$row['aggregate_local_id'],'entity_type'=>$row['entity_type'],'entity_uuid'=>$row['entity_uuid'],'entity_local_id'=>(int)$row['entity_local_id'],'event_type'=>$row['event_type'],'event_version'=>(int)$row['event_version'],'source_system'=>$row['source_system'],'payload_hash'=>$row['payload_hash'],'payload'=>json_decode($row['payload_json'],true,512,JSON_THROW_ON_ERROR)];
 $beforeHosted=(int)$source->query('SELECT COUNT(*) c FROM sync_outbox')->fetch_assoc()['c'];$hosted=$config;$hosted['role']='cloud';(new OperationalSyncEventService())->recordPurchaseOrderSnapshot($source,91,['config'=>$hosted]);poRestoreAssert((int)$source->query('SELECT COUNT(*) c FROM sync_outbox')->fetch_assoc()['c']===$beforeHosted,'hosted role must not emit reverse PO event');
 $unknown=$event['payload'];$unknown['unexpected']=true;unset($unknown['payload_hash']);$unknown['payload_hash']=hash('sha256',PurchaseOrderSyncPayloadService::encodeJson($unknown));poRestoreExpect(static fn()=>(new PurchaseOrderSyncPayloadService())->assertValid($unknown,$branch,$event),'PURCHASE_ORDER_SYNC_PAYLOAD_INVALID');
 poRestoreAssert(RestoreEventPhase::classify($event)===RestoreEventPhase::OPERATIONAL,'PO must be guarded operational restore');
 $result=(new SyncInboxService())->receiveBranchEvent($target,$branch,$event,SyncApplyMode::LIVE_APPLY);poRestoreAssert($result['status']==='processed','PO should restore');
 $order=$target->query('SELECT * FROM inventory_purchase_orders WHERE id=91')->fetch_assoc();poRestoreAssert($order['status']==='partially_received'&&(int)$order['sync_revision']===4,'PO lifecycle and revision should restore');
 $line=$target->query('SELECT * FROM inventory_purchase_order_lines WHERE id=911')->fetch_assoc();poRestoreAssert($line['received_qty']==='4.000000','PO progress should restore');poRestoreAssert((int)$target->query('SELECT COUNT(*) c FROM inventory_purchase_receipts')->fetch_assoc()['c']===0,'PO restore must not synthesize receipts');poRestoreAssert((int)$target->query('SELECT COUNT(*) c FROM inventory_movements')->fetch_assoc()['c']===0,'PO restore must not synthesize movements');
 $dup=(new SyncInboxService())->receiveBranchEvent($target,$branch,$event,SyncApplyMode::LIVE_APPLY);poRestoreAssert($dup['status']==='duplicate','exact PO replay should duplicate');
 $changed=$event;$changed['event_uuid']=SyncBranchIdentity::generateUuidV4();$changed['idempotency_key']='po-conflict:'.$changed['event_uuid'];$changed['payload']['purchase_order_lines'][0]['received_qty']='5.000000';poRestoreRehash($changed);$conflict=(new SyncInboxService())->receiveBranchEvent($target,$branch,$changed,SyncApplyMode::LIVE_APPLY);poRestoreAssert($conflict['status']==='conflict','same revision changed progress must conflict');poRestoreAssert($target->query('SELECT received_qty FROM inventory_purchase_order_lines WHERE id=911')->fetch_assoc()['received_qty']==='4.000000','conflict must not overwrite progress');
 $missing=$event;$missing['event_version']=5;$missing['payload']['sync_revision']=5;$missing['payload']['purchase_order']['sync_revision']=5;array_shift($missing['payload']['purchase_order_lines']);$missing['payload']['totals']['line_count']=1;poRestoreRehash($missing);poRestoreExpect(static fn()=>(new CloudOperationalMirrorService())->applyFromBranchEvent($target,$branch,$missing),'PURCHASE_ORDER_SYNC_MISSING_LINE_CONFLICT');poRestoreAssert((int)$target->query('SELECT COUNT(*) c FROM inventory_purchase_order_lines WHERE purchase_order_id=91')->fetch_assoc()['c']===2,'absence must not delete PO lines');
 echo "branch-restore-purchase-order-ok\n";
}finally{foreach([$source,$target] as $c)if($c instanceof mysqli)$c->close();foreach([$sourceDb,$targetDb] as $db)$admin->query("DROP DATABASE IF EXISTS `{$db}`");$admin->close();}
function poRestoreRehash(array &$event):void{unset($event['payload']['payload_hash']);$event['payload']['payload_hash']=hash('sha256',PurchaseOrderSyncPayloadService::encodeJson($event['payload']));$event['payload_hash']=hash('sha256',PurchaseOrderSyncPayloadService::encodeJson($event['payload']));}
function poRestoreExpect(callable $fn,string $code):void{try{$fn();}catch(Throwable $e){poRestoreAssert($e->getMessage()===$code,"expected {$code}, got {$e->getMessage()}");return;}throw new RuntimeException("Expected {$code}");}
function poRestoreAssert(bool $ok,string $message):void{if(!$ok)throw new RuntimeException($message);}
