<?php

return [
    'ajax/cash_flow_report.php' => ['permission' => 'reports.cash_flow', 'csrf' => '', 'lane' => 'erp'],
    'ajax/activate_table.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/clear_table.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/clear_table_normal.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/delete_order.php' => ['permission' => 'pos.cancel.unpaid', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/delivery_status_update.php' => ['permission' => 'delivery.dispatch', 'csrf' => 'delivery_dispatch', 'lane' => 'erp'],
    'ajax/get_tables.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/inventory_adjustment.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'ajax/inventory_count_approve.php' => ['permission' => 'inventory.approve', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/item_catalog_group_save.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'ajax/item_catalog_unit_save.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'ajax/sugar_spoons_assignments_save.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'ajax/merge_table_orders.php' => ['permission' => 'pos.table.merge', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/moova_change_order.php' => ['permission' => 'moova.accept', 'csrf' => 'moova_order', 'lane' => 'pos'],
    'ajax/moova_confirm_order.php' => ['permission' => 'moova.accept', 'csrf' => 'moova_order', 'lane' => 'pos'],
    'ajax/moova_disconnect_integration.php' => ['permission' => 'moova.manage', 'csrf' => 'moova_integration', 'lane' => 'erp'],
    'ajax/moova_save_integration.php' => ['permission' => 'moova.manage', 'csrf' => 'moova_integration', 'lane' => 'erp'],
    'ajax/move_table_order.php' => ['permission' => 'pos.table.move', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/process_split_payment.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/process_table_payment.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/print_dispatch.php' => [
        'any_of' => ['pos.open', 'pos.reprint', 'reports.view', 'reports.own_shift', 'pos.shift.close'],
        'csrf' => 'print_dispatch',
        'lane' => 'pos',
    ],
    'ajax/printer_health.php' => ['permission' => 'printers.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/team_hub.php' => ['any_of' => ['users.manage', 'roles.manage'], 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/pin_available.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'ajax/main_pin_login.php' => ['permission' => '', 'csrf' => 'main_pin', 'lane' => 'erp', 'public' => true],
    'ajax/main_session_lock.php' => ['permission' => '', 'csrf' => 'main_lock', 'lane' => 'erp'],
    'ajax/main_session_heartbeat.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'ajax/dismiss_pin_banner.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'ajax/pos_pin_login.php' => ['permission' => '', 'csrf' => 'pos_pin', 'lane' => 'erp'],
    'ajax/pos_lock.php' => ['permission' => '', 'csrf' => 'pos_pin', 'lane' => 'erp'],
    'ajax/pos_override_auth.php' => ['permission' => '', 'csrf' => 'pos_override', 'lane' => 'pos'],
    'ajax/pos_drawer_no_sale.php' => ['permission' => 'pos.drawer.no_sale', 'csrf' => 'pos_override', 'lane' => 'pos'],
    'ajax/pos_drawer_status.php' => ['any_of' => ['pos.drawer.no_sale', 'pos.open'], 'csrf' => '', 'lane' => 'pos'],
    'ajax/pulse_ajax.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'ajax/role_capabilities.php' => ['permission' => 'roles.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/user_permissions.php' => ['permission' => 'users.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/refund_order.php' => ['permission' => '', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/save_order.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/sync_credentials.php' => ['permission' => 'system.tools.run', 'csrf' => 'sync_credentials', 'lane' => 'erp', 'admin_or' => true],
    'ajax/update_customer_visit_end_time.php' => ['permission' => 'customers.manage', 'csrf' => 'customer_visits', 'lane' => 'erp', 'admin_or' => true],
    'ajax/update_table_status.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'close_shift.php' => ['permission' => 'pos.shift.close', 'csrf' => 'shift_close', 'lane' => 'pos'],
    'do/do_deletetask.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delprint.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delprod.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delptypes.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delservice.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_deluser.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_delzanka.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_edittask.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_logout.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'do/do_change_pin.php' => ['permission' => '', 'csrf' => 'change_pin', 'lane' => 'erp'],
    'do/do_record_shift_expense.php' => ['permission' => 'pos.cashdrawer.count', 'csrf' => 'shift_expense', 'lane' => 'pos'],
    'do/do_record_shift_payin.php' => ['permission' => 'pos.drawer.payin', 'csrf' => 'shift_payin', 'lane' => 'pos'],
    'do/do_record_shift_safe_drop.php' => ['permission' => 'pos.drawer.safe_drop', 'csrf' => 'shift_safe_drop', 'lane' => 'pos'],
    'do/do_force_close_drawer.php' => ['permission' => 'pos.shift.force_close', 'csrf' => 'shift_close', 'lane' => 'erp'],
    'do/do_takeover_drawer_session.php' => ['permission' => 'pos.shift.open', 'csrf' => 'shift_takeover', 'lane' => 'pos'],
    'do/do_transfer_drawer_register.php' => ['permission' => 'pos.shift.open', 'csrf' => 'shift_register_transfer', 'lane' => 'pos'],
    'do/do_start_drawer_override.php' => ['permission' => 'pos.shift.override', 'csrf' => 'shift_override', 'lane' => 'pos'],
    'do/do_end_drawer_override.php' => ['permission' => '', 'csrf' => 'shift_override', 'lane' => 'pos'],
    'do/do_begin_takeover_close_count.php' => ['permission' => 'pos.shift.force_close', 'csrf' => '', 'lane' => 'pos'],
    'do/do_submit_takeover_close_count.php' => ['permission' => 'pos.shift.force_close', 'csrf' => 'shift_takeover_count', 'lane' => 'pos'],
    'do/do_begin_shift_open_count.php' => ['permission' => 'pos.shift.open', 'csrf' => '', 'lane' => 'pos'],
    'do/do_submit_shift_open_count.php' => ['permission' => 'pos.shift.open', 'csrf' => 'shift_open_count', 'lane' => 'pos'],
    'do/do_begin_shift_close_count.php' => ['permission' => 'pos.shift.close', 'csrf' => '', 'lane' => 'pos'],
    'do/do_submit_shift_close_count.php' => ['permission' => 'pos.shift.close', 'csrf' => 'shift_close_count', 'lane' => 'pos'],
    'do/do_resolve_drawer_session.php' => ['permission' => 'pos.shift.resolve_variance', 'csrf' => 'shift_resolve', 'lane' => 'erp'],
    'do/do_set_opening_float_baseline.php' => ['permission' => 'pos.shift.set_opening_baseline', 'csrf' => 'shift_baseline', 'lane' => 'erp'],
    'do/do_set_business_day_cutoff.php' => [
        'any_of' => ['reports.cash_flow', 'pos.shift.close'],
        'csrf' => 'business_day_cutoff',
        'lane' => 'erp',
    ],
    'ajax/shift_unresolved_list.php' => ['permission' => 'pos.shift.resolve_variance', 'csrf' => '', 'lane' => 'erp'],
    'do/doadd_account.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_allowance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_booking.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_calcgroup.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_calcsalary.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_chance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_client.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_ctp copy.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_ctp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_customer_visit.php' => ['permission' => 'reports.view', 'csrf' => 'customer_visits', 'lane' => 'erp'],
    'do/doadd_cv.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_department.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_dis.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_docs.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_drug.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_empkbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_employee.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_group.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_group2.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_hiringcontract.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_hr_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_invoice.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/doadd_item.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_jop.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_joplevel.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_joprule.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_journal.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_kbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_manualfp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_mopfp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_multijournal.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_news.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_operation_step.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_order.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_presc.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_printer.php' => ['permission' => 'system.tools.run', 'csrf' => 'settings_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doadd_prod.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_production.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/doadd_ptype.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_rent.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_reservation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_role.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_team_create_role.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doadd_service.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_shift.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_task.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_town.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_unit.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_user.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doadd_visit.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_voucher.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_vtybe.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doassign_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dochange_password.php' => ['permission' => '', 'csrf' => 'password_change', 'lane' => 'erp'],
    'do/dodel_account.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/dodel_allowances.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_attdoc.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_client.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/dodel_contract.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_customer_visit.php' => ['permission' => 'reports.view', 'csrf' => 'customer_visits', 'lane' => 'erp'],
    'do/dodel_department.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_employee.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_employee_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_follow.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_fp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_group.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_group2.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_hr_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_invoice.php' => ['permission' => 'pos.cancel.unpaid', 'csrf' => 'pos_browser', 'lane' => 'pos', 'quarantined' => true],
    'do/dodel_item.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_jop.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_joplevel.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_joprule.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_kbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_operation_step.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_pro.php' => ['permission' => 'pos.cancel.unpaid', 'csrf' => 'pos_browser', 'lane' => 'pos', 'quarantined' => true],
    'do/dodel_production.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/dodel_reservation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_shift.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_task.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_town.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_unit.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_voucher.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/dodel_vtybe.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodelete_chance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_account.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doedit_allowances.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_chance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_client.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doedit_ctp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_cv.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_delivery_zone.php' => ['permission' => 'delivery.zones.manage', 'csrf' => 'delivery_zones_write', 'lane' => 'erp'],
    'do/doedit_department.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_employee.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_fp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_group.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_group2.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_hr_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_invoice.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/doedit_item.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_jop.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_joplevel.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_joprule.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_kbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_printer.php' => ['permission' => 'system.tools.run', 'csrf' => 'settings_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_prod.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_production.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/doedit_ptype.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_reservation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_role.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_role_permissions.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_restore_role_preset.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_service.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_settings.php' => ['permission' => 'system.tools.run', 'csrf' => 'settings_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_inventory_policy.php' => ['permission' => 'inventory.policy.manage', 'csrf' => 'inventory_policy_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_shift.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_town.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_unit.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_user.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_user_permissions.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_deactivate.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_reactivate.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_reset_pin.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_unlock_pin.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_voucher.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doedit_vtybe.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_zanka.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doeditclprofile.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doimportfp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dotest.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true],
    'do/doupdate_operation_status.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/get_shift_preview.php' => ['any_of' => ['pos.shift.close', 'pos.cashdrawer.count', 'pos.drawer.payin'], 'csrf' => 'shift_close', 'lane' => 'pos'],
    'do/importdata.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_station_save.php' => ['permission' => 'kds.manage', 'csrf' => 'kds_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_station_delete.php' => ['permission' => 'kds.manage', 'csrf' => 'kds_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_category_map_save.php' => ['permission' => 'kds.manage', 'csrf' => 'kds_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_worker_assign.php' => ['permission' => 'kds.manage', 'csrf' => 'kds_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_ticket_action.php' => ['permission' => 'kds.complete', 'csrf' => 'kds', 'lane' => 'erp'],
    'ajax/kds_tickets_list.php' => ['permission' => 'kds.view', 'csrf' => '', 'lane' => 'erp'],
    'ajax/kds_history.php' => ['permission' => 'kds.view', 'csrf' => '', 'lane' => 'erp'],
    'do/doadd_invoice_waiter.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos', 'quarantined' => true],
    'do/doadd_invoice_clothes.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/offline_sync.php' => ['permission' => 'system.tools.run', 'csrf' => 'offline_sync', 'lane' => 'erp', 'admin_or' => true],
    'do/pos_customer_delete.php' => ['permission' => 'customers.manage', 'csrf' => 'customers_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/pos_customer_merge.php' => ['permission' => 'customers.manage', 'csrf' => 'customers_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/reset_manual_prices.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/settle_credit.php' => ['permission' => 'pos.credit.settle', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/toggle_item_active.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/update_item_price.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/update_waiter_barcode.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/uploaditems.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do_close_shift_z.php' => ['permission' => 'pos.shift.close', 'csrf' => 'shift_close_z', 'lane' => 'pos'],

    // Completeness inventory: remaining ajax/do/print entry points
    'ajax/check_exact_barcode.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/cofe_create_order.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'ajax/current_user_capabilities.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'ajax/db_setup.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'ajax/delivery_assign.php' => ['permission' => 'delivery.assign', 'csrf' => 'delivery_operations', 'lane' => 'erp'],
    'ajax/delivery_orders_list.php' => ['permission' => 'delivery.dispatch', 'csrf' => '', 'lane' => 'erp'],
    'ajax/delivery_pending_count.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/delivery_plans.php' => ['any_of' => ['delivery.compensation.manage', 'delivery.workers.manage', 'delivery.settlements.manage', 'delivery.reports.view'], 'csrf' => 'delivery_operations', 'lane' => 'erp'],
    'ajax/delivery_settlements.php' => ['permission' => 'delivery.settlements.manage', 'csrf' => 'delivery_operations', 'lane' => 'erp'],
    'ajax/delivery_workers.php' => ['any_of' => ['delivery.assign', 'delivery.workers.manage', 'delivery.settlements.manage', 'delivery.reports.view'], 'csrf' => 'delivery_operations', 'lane' => 'erp'],
    'ajax/delivery_zones_list.php' => ['any_of' => ['pos.open', 'delivery.dispatch', 'delivery.assign', 'delivery.zones.manage', 'delivery.compensation.manage', 'delivery.workers.manage', 'delivery.settlements.manage', 'delivery.reports.view'], 'csrf' => '', 'lane' => 'erp'],
    'ajax/get_category_items.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_daily_sales.php' => ['any_of' => ['pos.open', 'reports.view'], 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_item_variants.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/item_sugar_spoons_toggle.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'ajax/get_items.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_pos_options.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_recent_orders.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_table_amount.php' => ['permission' => 'pos.table.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_table_items.php' => ['permission' => 'pos.table.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/get_table_order.php' => ['permission' => 'pos.table.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/inventory_count_close.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/inventory_count_create.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/inventory_count_reverse.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/inventory_count_save.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/inventory_count_submit.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/inventory_item_quick_create.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_receiving', 'lane' => 'erp'],
    'ajax/inventory_purchase_order.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_receiving', 'lane' => 'erp'],
    'ajax/inventory_purchase_receive.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_receiving', 'lane' => 'erp'],
    'ajax/inventory_reason_code.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_reason_code', 'lane' => 'erp'],
    'ajax/inventory_stock_level_bulk.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_stock_level', 'lane' => 'erp'],
    'ajax/inventory_stock_level_save.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_stock_level', 'lane' => 'erp'],
    'ajax/inventory_transfer_cancel.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_transfer', 'lane' => 'erp'],
    'ajax/inventory_transfer_close_variance.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_transfer', 'lane' => 'erp'],
    'ajax/inventory_transfer_receive.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_transfer', 'lane' => 'erp'],
    'ajax/inventory_transfer_save.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_transfer', 'lane' => 'erp'],
    'ajax/inventory_transfer_send.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_transfer', 'lane' => 'erp'],
    'ajax/inventory_transfer_submit.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_transfer', 'lane' => 'erp'],
    'ajax/load_items_lazy.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/load_order.php' => ['permission' => 'pos.table.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/manager_approval.php' => ['permission' => 'pos.recipe_stock_override', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/moova_menu_sync_payload.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/pos_customer_profile.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/pos_customer_save.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/pos_customer_search.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/pos_delivery_queue.php' => ['permission' => 'pos.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/pos_customers_admin_detail.php' => ['permission' => 'customers.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/pos_customers_admin_list.php' => ['permission' => 'customers.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/pos_write_recovery_status.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/recipe_editor_lookup.php' => ['permission' => 'inventory.edit', 'csrf' => '', 'lane' => 'erp'],
    'ajax/search_item.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/search_item_supermarket.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/search_items.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/search_items_advanced.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'ajax/search_items_autocomplete.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'do/debug_columns.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/debug_ot_head.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/debug_post.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/debug_schema.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/debug_schema_2.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/doadd_start_balance.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/doadd_store.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/dobackup.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/docreatedatabase.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true, 'quarantined' => true],
    'do/dosearch.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'print/br2538.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'print/closed_session_items.php' => [
        'any_of' => ['reports.cash_flow', 'pos.shift.close'],
        'csrf' => '',
        'lane' => 'erp',
    ],
    'print/closed_session_receipt.php' => [
        'any_of' => ['reports.cash_flow', 'pos.shift.close'],
        'csrf' => '',
        'lane' => 'erp',
    ],
    'print/contracta4.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'print/daily_sales_receipt.php' => ['permission' => 'pos.shift.close', 'csrf' => '', 'lane' => 'pos'],
    'print/freebarcode.php' => ['permission' => 'pos.reprint', 'csrf' => '', 'lane' => 'pos'],
    'print/pre_clients.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'print/preparation.php' => ['any_of' => ['pos.open', 'pos.reprint'], 'csrf' => '', 'lane' => 'pos'],
    'print/presc_print.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'print/print_sales.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'print/receipt.php' => ['any_of' => ['pos.open', 'pos.reprint'], 'csrf' => '', 'lane' => 'pos'],
    'print/receipt_waiter.php' => ['any_of' => ['pos.open', 'pos.reprint'], 'csrf' => '', 'lane' => 'pos'],
    'print/shift_sales_receipt.php' => ['permission' => 'pos.shift.close', 'csrf' => '', 'lane' => 'pos'],

    // Shared endpoint includes. They are shipped for runtime inclusion but may
    // never execute as standalone HTTP routes.
    'ajax/inventory_count_common.php' => ['internal' => true, 'lane' => 'erp'],
    'ajax/inventory_transfer_common.php' => ['internal' => true, 'lane' => 'erp'],
    'api/admin/updates/_bootstrap.php' => ['internal' => true, 'lane' => 'erp'],
    'api/moova_menu_api_auth.php' => ['internal' => true, 'lane' => 'erp'],
    'print/includes/connect.php' => ['internal' => true, 'lane' => 'erp'],
    'print/includes/footer.php' => ['internal' => true, 'lane' => 'erp'],
    'print/includes/header.php' => ['internal' => true, 'lane' => 'erp'],

    // HTTP APIs with their own token/HMAC/session authorization. The central
    // guard classifies them; endpoint_auth does not replace their own checks.
    'api/admin/updates/check.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/admin/updates/start.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/admin/updates/status.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/categories.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/health.php' => ['public' => true, 'lane' => 'erp'],
    'api/items.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/moova/ack_branch_events.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/moova/branch_events.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/pos/index.php' => ['permission' => 'pos.open', 'csrf' => '', 'lane' => 'pos'],
    'api/ready.php' => ['public' => true, 'lane' => 'erp'],
    'api/sync/ack_branch_events.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/branch_events.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/export_branch_image.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/export_branch_restore.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/pairing_status.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/receive_branch_events.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/receive_branch_image.php' => ['endpoint_auth' => true, 'lane' => 'erp'],
    'api/sync/status.php' => ['endpoint_auth' => true, 'lane' => 'erp'],

    // Legacy read helpers now use the same session and named-permission guard
    // as ajax/do/print routes.
    'get/check_barcode.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'get/chk_client.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'get/get_accinfo.php' => ['permission' => 'accounting.view', 'csrf' => '', 'lane' => 'erp'],
    'get/get_barcode_info.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'get/get_bvalue.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'get/get_iteminfo.php' => ['any_of' => ['pos.open', 'menu.edit'], 'csrf' => '', 'lane' => 'erp'],
    'get/get_price1.php' => ['any_of' => ['pos.open', 'menu.edit'], 'csrf' => '', 'lane' => 'erp'],
    'get/iname.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'get/refresh_acc.php' => ['permission' => 'accounting.view', 'csrf' => '', 'lane' => 'erp'],
    'get/refresh_items.php' => ['any_of' => ['pos.open', 'menu.edit'], 'csrf' => '', 'lane' => 'erp'],

    // Unsafe/broken legacy utilities remain in source history but are absent
    // from the commercial artifact.
    'do/dbase/do_turncate.php' => ['quarantined' => true, 'lane' => 'erp'],
    'do/start/doaddinstallment.php' => ['quarantined' => true, 'lane' => 'erp'],
    'do/start/dodel_rent.php' => ['quarantined' => true, 'lane' => 'erp'],
    'get/export_summery_excel.php' => ['quarantined' => true, 'lane' => 'erp'],
    'get/reduce_remain.php' => ['quarantined' => true, 'lane' => 'erp'],
];
