<?php

return [
    'ajax/cash_flow_report.php' => ['permission' => 'reports.cash_flow', 'csrf' => '', 'lane' => 'erp'],
    'ajax/activate_table.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/clear_table.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/clear_table_normal.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/delete_order.php' => ['permission' => 'pos.cancel.unpaid', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/delivery_status_update.php' => ['permission' => 'delivery.dispatch', 'csrf' => 'delivery_dispatch', 'lane' => 'erp'],
    'ajax/generate_items.php' => ['permission' => 'system.tools.run', 'csrf' => 'generate_items', 'lane' => 'erp', 'admin_or' => true],
    'ajax/get_tables.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/inventory_adjustment.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'ajax/inventory_count_approve.php' => ['permission' => 'inventory.approve', 'csrf' => 'inventory_count', 'lane' => 'erp'],
    'ajax/item_catalog_group_save.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'ajax/item_catalog_unit_save.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'ajax/merge_table_orders.php' => ['permission' => 'pos.table.merge', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/moova_change_order.php' => ['permission' => 'moova.manage', 'csrf' => 'moova_order', 'lane' => 'erp'],
    'ajax/moova_confirm_order.php' => ['permission' => 'moova.accept', 'csrf' => 'moova_order', 'lane' => 'erp'],
    'ajax/moova_disconnect_integration.php' => ['permission' => 'moova.manage', 'csrf' => 'moova_integration', 'lane' => 'erp'],
    'ajax/moova_save_integration.php' => ['permission' => 'moova.manage', 'csrf' => 'moova_integration', 'lane' => 'erp'],
    'ajax/move_table_order.php' => ['permission' => 'pos.table.move', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/process_split_payment.php' => ['permission' => 'pos.split', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/process_table_payment.php' => ['permission' => 'pos.payment.take', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/team_hub.php' => ['any_of' => ['users.manage', 'roles.manage'], 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/pin_available.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'ajax/pos_pin_login.php' => ['permission' => '', 'csrf' => 'pos_pin', 'lane' => 'erp'],
    'ajax/pos_lock.php' => ['permission' => '', 'csrf' => 'pos_pin', 'lane' => 'erp'],
    'ajax/pos_override_auth.php' => ['permission' => '', 'csrf' => 'pos_override', 'lane' => 'pos'],
    'ajax/pos_drawer_no_sale.php' => ['permission' => 'pos.drawer.no_sale', 'csrf' => 'pos_override', 'lane' => 'pos'],
    'ajax/pos_drawer_status.php' => ['any_of' => ['pos.drawer.no_sale', 'pos.open'], 'csrf' => '', 'lane' => 'pos'],
    'ajax/pulse_ajax.php' => ['permission' => 'reports.view', 'csrf' => '', 'lane' => 'erp'],
    'ajax/role_capabilities.php' => ['permission' => 'roles.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/user_permissions.php' => ['permission' => 'users.manage', 'csrf' => '', 'lane' => 'erp', 'admin_or' => true],
    'ajax/refund_order.php' => ['permission' => 'pos.refund', 'csrf' => 'pos_browser', 'lane' => 'pos', 'admin_or' => true],
    'ajax/save_order.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'ajax/sync_credentials.php' => ['permission' => 'system.tools.run', 'csrf' => 'sync_credentials', 'lane' => 'erp', 'admin_or' => true],
    'ajax/update_customer_visit_end_time.php' => ['permission' => 'customers.manage', 'csrf' => 'customer_visits', 'lane' => 'erp', 'admin_or' => true],
    'ajax/update_table_status.php' => ['permission' => 'pos.table.open', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'close_shift.php' => ['permission' => 'pos.shift.close', 'csrf' => 'shift_close', 'lane' => 'pos'],
    'do/do_deletetask.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delprint.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delprod.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delptypes.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_delservice.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_deluser.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_delzanka.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_edittask.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/do_logout.php' => ['permission' => '', 'csrf' => '', 'lane' => 'erp'],
    'do/do_record_shift_expense.php' => ['permission' => 'pos.cashdrawer.count', 'csrf' => 'shift_expense', 'lane' => 'pos'],
    'do/do_record_shift_payin.php' => ['permission' => 'pos.drawer.payin', 'csrf' => 'shift_payin', 'lane' => 'pos'],
    'do/do_record_shift_safe_drop.php' => ['permission' => 'pos.drawer.safe_drop', 'csrf' => 'shift_safe_drop', 'lane' => 'pos'],
    'do/do_force_close_drawer.php' => ['permission' => 'pos.shift.force_close', 'csrf' => 'shift_close', 'lane' => 'pos'],
    'do/doadd_account.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_allowance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_booking.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_calcgroup.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_calcsalary.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_chance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_client.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_ctp copy.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_ctp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_customer_visit.php' => ['permission' => 'reports.view', 'csrf' => 'customer_visits', 'lane' => 'erp'],
    'do/doadd_cv.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_department.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_dis.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_docs.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_drug.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_empkbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_employee.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_group.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_group2.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_hiringcontract.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_hr_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_invoice.php' => ['permission' => 'pos.sell.takeaway', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/doadd_item.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_jop.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_joplevel.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_joprule.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_journal.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_kbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_manualfp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_mopfp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_multijournal.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_news.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_operation_step.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_order.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_presc.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_printer.php' => ['permission' => 'system.tools.run', 'csrf' => 'settings_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doadd_prod.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_production.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/doadd_ptype.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_rent.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_reservation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_role.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_team_create_role.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doadd_service.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_shift.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_task.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_town.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_unit.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doadd_user.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doadd_visit.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doadd_voucher.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doadd_vtybe.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doassign_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dochange_password.php' => ['permission' => '', 'csrf' => 'password_change', 'lane' => 'erp'],
    'do/dodel_account.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/dodel_allowances.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_attdoc.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_client.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/dodel_contract.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_customer_visit.php' => ['permission' => 'reports.view', 'csrf' => 'customer_visits', 'lane' => 'erp'],
    'do/dodel_department.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_employee.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_employee_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_follow.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_fp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_group.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_group2.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_hr_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_invoice.php' => ['permission' => 'pos.cancel.unpaid', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/dodel_item.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_jop.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_joplevel.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_joprule.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_kbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_operation_step.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_pro.php' => ['permission' => 'pos.cancel.unpaid', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/dodel_production.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/dodel_reservation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_shift.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_task.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_town.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodel_unit.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/dodel_voucher.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/dodel_vtybe.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dodelete_chance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_account.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doedit_allowances.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_chance.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_client.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doedit_ctp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_cv.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_delivery_zone.php' => ['permission' => 'delivery.zones.manage', 'csrf' => 'delivery_zones', 'lane' => 'erp'],
    'do/doedit_department.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_employee.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_fp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_group.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_group2.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_hr_operation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_invoice.php' => ['permission' => 'pos.sell.takeaway', 'csrf' => 'pos_browser', 'lane' => 'pos'],
    'do/doedit_item.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_jop.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_joplevel.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_joprule.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_kbi.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_printer.php' => ['permission' => 'system.tools.run', 'csrf' => 'settings_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_prod.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_production.php' => ['permission' => 'inventory.edit', 'csrf' => 'inventory_adjustment', 'lane' => 'erp'],
    'do/doedit_ptype.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_reservation.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_role.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_role_permissions.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_restore_role_preset.php' => ['permission' => 'roles.manage', 'csrf' => 'roles_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_service.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_settings.php' => ['permission' => 'system.tools.run', 'csrf' => 'settings_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_shift.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_town.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_unit.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/doedit_user.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_user_permissions.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_deactivate.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_reactivate.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_reset_pin.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/do_user_unlock_pin.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/doedit_voucher.php' => ['permission' => 'accounting.view', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/doedit_vtybe.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doedit_zanka.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doeditclprofile.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/doimportfp.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/dotest.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true],
    'do/doupdate_operation_status.php' => ['permission' => 'reports.view', 'csrf' => 'hr_write', 'lane' => 'erp'],
    'do/get_shift_preview.php' => ['any_of' => ['pos.shift.close', 'pos.cashdrawer.count', 'pos.drawer.payin'], 'csrf' => 'shift_close', 'lane' => 'pos'],
    'do/importdata.php' => ['permission' => 'system.tools.run', 'csrf' => 'default', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_station_save.php' => ['permission' => 'kds.manage', 'csrf' => 'kds_settings', 'lane' => 'erp', 'admin_or' => true],
    'do/kds_ticket_action.php' => ['permission' => 'kds.complete', 'csrf' => 'kds_ticket', 'lane' => 'erp'],
    'do/offline_sync.php' => ['permission' => 'system.tools.run', 'csrf' => 'offline_sync', 'lane' => 'erp', 'admin_or' => true],
    'do/pos_customer_delete.php' => ['permission' => 'customers.manage', 'csrf' => 'customers_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/pos_customer_merge.php' => ['permission' => 'customers.manage', 'csrf' => 'customers_manage', 'lane' => 'erp', 'admin_or' => true],
    'do/recost.php' => ['permission' => 'inventory.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/reset_manual_prices.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/settle_credit.php' => ['permission' => 'pos.credit.settle', 'csrf' => 'accounting_write', 'lane' => 'erp'],
    'do/toggle_item_active.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/update_item_price.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do/update_waiter_barcode.php' => ['permission' => 'users.manage', 'csrf' => 'users_write', 'lane' => 'erp', 'admin_or' => true],
    'do/uploaditems.php' => ['permission' => 'menu.edit', 'csrf' => 'menu_write', 'lane' => 'erp'],
    'do_close_shift_z.php' => ['permission' => 'pos.shift.close', 'csrf' => 'shift_close_z', 'lane' => 'pos'],
];
