<?php

/**
 * ERP HTML page permission manifest.
 * Keys are page filenames relative to project root.
 */
return [
    // user admin
    'users.php' => ['permission' => 'users.manage', 'admin_or' => true],
    'team.php' => ['any_of' => ['users.manage', 'roles.manage'], 'admin_or' => true],
    'add_user.php' => ['permission' => 'users.manage', 'admin_or' => true],
    'edit_user.php' => ['permission' => 'users.manage', 'admin_or' => true],
    'myroles.php' => ['permission' => 'roles.manage', 'admin_or' => true],
    'add_role.php' => ['permission' => 'roles.manage', 'admin_or' => true],
    'edit_role.php' => ['permission' => 'roles.manage', 'admin_or' => true],
    'role_permissions.php' => ['permission' => 'roles.manage', 'admin_or' => true],
    'setting.php' => ['permission' => 'system.tools.run', 'admin_or' => true],
    'change_password.php' => ['permission' => null],
    'change_pin.php' => ['permission' => null],
    'workspace.php' => ['permission' => null],
    'no_access.php' => ['permission' => null],
    'register_pair.php' => ['permission' => null],
    'dashboard.php' => ['permission' => null],

    // menu / inventory
    'myitems.php' => ['permission' => 'menu.edit'],
    'add_item.php' => ['permission' => 'menu.edit'],
    'mystores.php' => ['permission' => 'inventory.edit'],
    'items_factory.php' => ['permission' => 'menu.edit'],
    'inv_operations.php' => ['permission' => 'inventory.edit'],
    'inventory_dashboard.php' => ['permission' => 'inventory.edit'],
    'inventory_reports.php' => ['permission' => 'inventory.edit'],
    'inventory_purchasing.php' => ['permission' => 'inventory.edit'],
    'inventory_counts.php' => ['permission' => 'inventory.edit'],
    'inventory_transfers.php' => ['permission' => 'inventory.edit'],
    'inventory_adjustments.php' => ['permission' => 'inventory.edit'],
    'inventory_stock_levels.php' => ['permission' => 'inventory.edit'],
    'inventory_stores.php' => ['permission' => 'inventory.edit'],
    'inventory_reason_codes.php' => ['permission' => 'inventory.edit'],

    // accounting
    'vouchers.php' => ['permission' => 'accounting.view'],
    'add_voucher.php' => ['permission' => 'accounting.view'],
    'add_journal.php' => ['permission' => 'accounting.view'],
    'addmulti_journal.php' => ['permission' => 'accounting.view'],
    'daily_journal.php' => ['permission' => 'accounting.view'],
    'myaccounts.php' => ['permission' => 'accounting.view'],
    'acc_report.php' => ['permission' => 'accounting.view'],
    'add_account.php' => ['permission' => 'accounting.view'],
    'edit_account.php' => ['permission' => 'accounting.view'],

    // reports / HR
    'reports.php' => ['permission' => 'reports.view'],
    'shift_sales_report.php' => ['permission' => 'reports.view'],
    'stagnant-items-report.php' => ['permission' => 'reports.view'],
    'items_summery.php' => ['permission' => 'reports.view'],
    'calcsalary.php' => ['permission' => 'reports.view'],
    'attandance.php' => ['permission' => 'reports.view'],
    'orders.php' => ['permission' => 'reports.view'],
    'employees.php' => ['permission' => 'reports.view'],
    'departments.php' => ['permission' => 'reports.view'],
    'hr_operations.php' => ['permission' => 'reports.view'],
    'add_shift.php' => ['permission' => 'reports.view'],
    'news.php' => ['permission' => 'reports.view'],
    'add_news.php' => ['permission' => 'reports.view'],
    'booking.php' => ['permission' => 'reports.view'],
    'add_reservation.php' => ['permission' => 'reports.view'],
    'edit_reservation.php' => ['permission' => 'reports.view'],
    'customer_visits.php' => ['permission' => 'reports.view'],
    'add_customer_visit.php' => ['permission' => 'reports.view'],
    'pulse.php' => ['permission' => 'reports.view'],
    'pulse_stats.php' => ['permission' => 'reports.view'],

    // POS lanes
    'pos_barcode.php' => ['permission' => 'pos.open'],
    'pos_supermarket.php' => ['permission' => 'pos.open'],
    'pos_clothes.php' => ['permission' => 'pos.open'],
    'pos_tables.php' => ['permission' => 'pos.table.open'],
    'pos_session_status.php' => ['permission' => 'pos.open'],

    // POS admin
    'pos_customers.php' => ['permission' => 'customers.manage', 'admin_or' => true],
    'closed_sessions.php' => ['permission' => 'pos.shift.close'],
    'cash_flow_report.php' => ['permission' => 'reports.cash_flow'],
    'drawer_session.php' => ['permission' => 'reports.cash_flow'],
    'z_report.php' => ['permission' => 'pos.shift.close'],

    // delivery / moova / kds
    'moova_integration.php' => ['permission' => 'moova.manage'],
    'delivery_board.php' => ['permission' => 'delivery.dispatch'],
    'delivery_zones.php' => ['permission' => 'delivery.zones.manage'],
    'kds.php' => ['permission' => 'kds.view'],
    'kds_settings.php' => ['permission' => 'kds.manage', 'admin_or' => true],
    // Station board is for assigned kitchen workers (view), not settings admins only.
    'kds_station.php' => ['permission' => 'kds.view'],

    // Completeness inventory: remaining root HTML entry points
    'about.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'accattlogs.php' => ['permission' => 'reports.view'],
    'accounts.php' => ['permission' => 'accounting.view'],
    'add_allowances.php' => ['permission' => 'reports.view'],
    'add_booking.php' => ['permission' => 'reports.view'],
    'add_calcsalary.php' => ['permission' => 'reports.view'],
    'add_call.php' => ['permission' => 'reports.view'],
    'add_client.php' => ['permission' => 'accounting.view'],
    'add_cv.php' => ['permission' => 'reports.view'],
    'add_department.php' => ['permission' => 'reports.view'],
    'add_drugs.php' => ['permission' => 'reports.view'],
    'add_empkbi.php' => ['permission' => 'reports.view'],
    'add_employee.php' => ['permission' => 'accounting.view'],
    'add_externalcontract.php' => ['permission' => 'reports.view'],
    'add_hiringcontract.php' => ['permission' => 'reports.view'],
    'add_hr_operation.php' => ['permission' => 'reports.view'],
    'add_jop.php' => ['permission' => 'reports.view'],
    'add_joplevel.php' => ['permission' => 'reports.view'],
    'add_joprule.php' => ['permission' => 'reports.view'],
    'add_kbi.php' => ['permission' => 'reports.view'],
    'add_manual_price_column.php' => ['permission' => 'menu.edit'],
    'add_manualfp.php' => ['permission' => 'reports.view'],
    'add_order.php' => ['permission' => 'reports.view'],
    'add_permit.php' => ['permission' => 'reports.view'],
    'add_production.php' => ['permission' => 'inventory.edit'],
    'add_rent.php' => ['permission' => 'accounting.view'],
    'add_rese.php' => ['permission' => 'reports.view'],
    'add_store.php' => ['permission' => 'inventory.edit'],
    'add_task.php' => ['permission' => 'reports.view'],
    'add_trainingcontract.php' => ['permission' => 'reports.view'],
    'add_visit.php' => ['permission' => 'reports.view'],
    'add_vtybe.php' => ['permission' => 'reports.view'],
    'add_zanka.php' => ['permission' => 'reports.view'],
    'allowences.php' => ['permission' => 'reports.view'],
    'barcode_designer.php' => ['permission' => 'menu.edit'],
    'barcode_search.php' => ['permission' => 'menu.edit'],
    'blogcontent.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'bookings.php' => ['permission' => 'reports.view'],
    'calls.php' => ['permission' => 'reports.view'],
    'chances.php' => ['permission' => 'reports.view'],
    'check_db_structure.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'check_orders.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'check_payments.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'check_table_structure.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'clients.php' => ['permission' => 'accounting.view'],
    'clprofile.php' => ['permission' => 'accounting.view'],
    'clprofile2.php' => ['permission' => 'accounting.view'],
    'conectedmachines.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'create_acc_head_table.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'crud_tables.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'customer_visits_stats.php' => ['permission' => 'reports.view'],
    'cvs.php' => ['permission' => 'reports.view'],
    'debug.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'debug_bank.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'debug_db.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'debug_delivery.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'debug_jal.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'debug_tasks.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'delete_fix_file.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'deletezanka.php' => ['permission' => 'reports.view'],
    'doimport.php' => ['permission' => 'accounting.view'],
    'drugs.php' => ['permission' => 'reports.view'],
    'edit_allowances.php' => ['permission' => 'reports.view'],
    'edit_client.php' => ['permission' => 'accounting.view'],
    'edit_contract.php' => ['permission' => 'reports.view'],
    'edit_cv.php' => ['permission' => 'reports.view'],
    'edit_department.php' => ['permission' => 'reports.view'],
    'edit_drugs.php' => ['permission' => 'reports.view'],
    'edit_employee.php' => ['permission' => 'reports.view'],
    'edit_hr_operation.php' => ['permission' => 'reports.view'],
    'edit_item.php' => ['permission' => 'menu.edit'],
    'edit_jop.php' => ['permission' => 'reports.view'],
    'edit_joplevel.php' => ['permission' => 'reports.view'],
    'edit_joprule.php' => ['permission' => 'reports.view'],
    'edit_manualfp.php' => ['permission' => 'reports.view'],
    'edit_order.php' => ['permission' => 'reports.view'],
    'edit_production.php' => ['permission' => 'inventory.edit'],
    'edit_res.php' => ['permission' => 'reports.view'],
    'edit_rese.php' => ['permission' => 'reports.view'],
    'edit_shift.php' => ['permission' => 'reports.view'],
    'edit_task.php' => ['permission' => 'reports.view'],
    'edit_visit.php' => ['permission' => 'reports.view'],
    'edit_zanka.php' => ['permission' => 'reports.view'],
    'emp_kbis.php' => ['permission' => 'reports.view'],
    'employee_operations.php' => ['permission' => 'reports.view'],
    'emprofile.php' => ['permission' => 'reports.view'],
    'example.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'externalcontracts.php' => ['permission' => 'reports.view'],
    'fat.php' => ['permission' => 'pos.open'],
    'fat1.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'fix_database.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'fix_journal_entries.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'fix_passwords.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'followup.php' => ['permission' => 'reports.view'],
    'forbidden.php' => ['permission' => null],
    'generate-examples.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'generate-verified-files.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'get_barcode.php' => ['permission' => 'menu.edit'],
    'hiringcontracts.php' => ['permission' => 'reports.view'],
    'importfplog.php' => ['permission' => 'accounting.view'],
    'index.php' => ['permission' => null, 'public' => true],
    'index2.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'indexmop.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'inventory_count_detail.php' => ['permission' => 'inventory.edit'],
    'inventory_transfer_detail.php' => ['permission' => 'inventory.edit'],
    'invoice.php' => ['permission' => 'pos.open'],
    'item_categories.php' => ['permission' => 'menu.edit'],
    'item_summery.php' => ['permission' => 'reports.view'],
    'items_report.php' => ['permission' => 'reports.view'],
    'items_start_balance.php' => ['permission' => 'inventory.edit'],
    'joplevels.php' => ['permission' => 'reports.view'],
    'joprules.php' => ['permission' => 'reports.view'],
    'jops.php' => ['permission' => 'reports.view'],
    'kbis.php' => ['permission' => 'reports.view'],
    'list_columns.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'logs_viewer.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'machinelog.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'manualattandance.php' => ['permission' => 'reports.view'],
    'moova_pos_proxy.php' => ['permission' => 'moova.manage'],
    'moova_pos_widget.php' => ['permission' => 'moova.manage'],
    'mop.php' => ['permission' => 'pos.open'],
    'mygroups.php' => ['permission' => 'menu.edit'],
    'myrentables.php' => ['permission' => 'accounting.view'],
    'mytowns.php' => ['permission' => 'reports.view'],
    'myunits.php' => ['permission' => 'menu.edit'],
    'not_licenced.php' => ['permission' => null, 'public' => true],
    'operations.php' => ['permission' => 'reports.view'],
    'operations_summary.php' => ['permission' => 'reports.view'],
    'optimize_assets.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'patients.php' => ['permission' => 'reports.view'],
    'permits.php' => ['permission' => 'reports.view'],
    'pos_simple.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'pos_sync.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'pos_time.php' => ['permission' => 'pos.open'],
    'pre_start.php' => ['permission' => null, 'public' => true],
    'presc.php' => ['permission' => 'reports.view'],
    'print_my_shift.php' => ['permission' => 'reports.own_shift'],
    'production.php' => ['permission' => 'inventory.edit'],
    'pulse_types.php' => ['permission' => 'reports.view'],
    'quick_fix.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'recipe_audit_report.php' => ['permission' => 'inventory.edit'],
    'recipe_editor.php' => ['permission' => 'inventory.edit'],
    'recipe_manage.php' => ['permission' => 'inventory.edit'],
    'recipe_operational_dashboard.php' => ['permission' => 'inventory.edit'],
    'recipe_operations_report.php' => ['permission' => 'inventory.edit'],
    'recipe_production.php' => ['permission' => 'inventory.edit'],
    'recipe_stock_reconciliation.php' => ['permission' => 'inventory.edit'],
    'refresh_balances.php' => ['permission' => 'inventory.edit'],
    'rentables.php' => ['permission' => 'accounting.view'],
    'rentcontracts.php' => ['permission' => 'accounting.view'],
    'repair_database_jal.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'reps_cl.php' => ['permission' => 'accounting.view'],
    'rese.php' => ['permission' => 'reports.view'],
    'reservations.php' => ['permission' => 'reports.view'],
    'roadmap.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'run_migrations.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'run_payment_updates.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'run_table_updates.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'run_update_006.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'run_update_007.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'sales-by-day.php' => ['permission' => 'reports.view'],
    'sales-by-group.php' => ['permission' => 'reports.view'],
    'sales-by-hour.php' => ['permission' => 'reports.view'],
    'sales-by-month.php' => ['permission' => 'reports.view'],
    'sales-by-week.php' => ['permission' => 'reports.view'],
    'sales-reports.php' => ['permission' => 'reports.view'],
    'sales.php' => ['permission' => 'reports.view'],
    'save_start_balance.php' => ['permission' => 'inventory.edit'],
    'scan_att.php' => ['permission' => 'reports.view'],
    'setup_demo_data.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'shifts.php' => ['permission' => 'reports.view'],
    'sql_error.php' => ['permission' => null, 'public' => true],
    'stamp-add.php' => ['permission' => 'menu.edit'],
    'start_balance.php' => ['permission' => 'inventory.edit'],
    'summary.php' => ['permission' => 'reports.view'],
    'tables.php' => ['permission' => 'pos.table.open'],
    'tasks.php' => ['permission' => 'reports.view'],
    'top_products_report.php' => ['permission' => 'reports.view'],
    'trainingcontracts.php' => ['permission' => 'reports.view'],
    'update.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'view_logs.php' => ['permission' => 'system.tools.run', 'admin_or' => true, 'quarantined' => true],
    'visits.php' => ['permission' => 'reports.view'],
    'vtybes.php' => ['permission' => 'reports.view'],
    'waiter_barcode.php' => ['permission' => 'users.manage', 'admin_or' => true],
    'warning.php' => ['permission' => null],
];
