<?php

/**
 * Commercial V1 Step 1 release packaging policy.
 *
 * Packaging starts from committed/tracked source and keeps only paths that
 * match an allow rule. Deny rules are hard failures if they would be included.
 *
 * @return array{
 *   allow_directories: list<string>,
 *   allow_root_globs: list<string>,
 *   deny_path_prefixes: list<string>,
 *   deny_path_exact: list<string>,
 *   deny_name_globs: list<string>
 * }
 */
return [
    'allow_directories' => [
        'ajax',
        'api',
        'classes',
        'config',
        'css',
        'dist',
        'do',
        'fonts',
        'images',
        'img',
        'includes',
        'js',
        'lang',
        'PhpSpreadsheet',
        'print',
        'src',
        'vendor',
    ],
    'allow_root_globs' => [
        '.htaccess',
        'Caddyfile',
        'LICENSE',
        'LICENSE.md',
        'composer.json',
        'composer.lock',
        'package.json',
        'package-lock.json',
        'favicon.ico',
        'robots.txt',
        '*.php',
        '*.js',
        '*.css',
        '*.map',
        '*.png',
        '*.jpg',
        '*.jpeg',
        '*.gif',
        '*.svg',
        '*.webp',
        '*.ico',
        '*.woff',
        '*.woff2',
        '*.ttf',
        '*.eot',
    ],
    'deny_path_prefixes' => [
        'tools/',
        'tests/',
        'docs/',
        'cli/',
        'deploy/',
        'backup/',
        'logs/',
        'var/',
        'db/',
        'dbase/',
        'update/',
        'scripts/',
        'output/',
        'uploads/',
        '.git/',
        '.github/',
        '.cursor/',
        'node_modules/',
        'agent-transcripts/',
    ],
    'deny_path_exact' => require __DIR__ . '/prohibited_web_routes.php',
    'deny_name_globs' => [
        'debug_*.php',
        'check_*.php',
        'fix_*.php',
        'repair_*.php',
        'setup_demo*.php',
        'run_*_updates.php',
        'run_migrations.php',
        '*.sql',
        '*.log',
        '*.bak',
        '.env',
        '.env.*',
    ],
];
