<?php

/**
 * Commercial V1 web-artifact policy.
 *
 * The modern manifest-aware builder and the Step 1 compatibility gate consume
 * the same fail-closed policy. Runtime uploads and repository-only material are
 * never packaged.
 */
return [
    'version' => 1,
    'endpoint_directories' => ['ajax', 'api', 'do', 'get', 'print'],
    'endpoint_internal_files' => [],
    'root_internal_files' => [
        'phpstan-bootstrap.php',
    ],
    'root_runtime_files' => [
        '.htaccess',
        'Caddyfile',
        'LICENSE',
        'LICENSE.md',
        'entrypoint.sh',
        'php.ini',
        'pos_config.json',
        'pos_offline.html',
        'pos_sw.js',
        'qrCode.png',
        'sw.js',
        'version.json',
        'version.txt',
    ],
    'runtime_prefixes' => [
        'PhpSpreadsheet/',
        'assets/',
        'classes/',
        'components/',
        'config/',
        'css/',
        'dist/',
        'elements/',
        'fonts/',
        'images/',
        'img/',
        'includes/',
        'js/',
        'lang/',
        'language/',
        'plugins/',
        'src/',
        'vendor/',
    ],
    'runtime_exact_files' => [
        'barcodegr/LICENSE.md',
    ],
    'runtime_library_prefixes' => [
        'barcodegr/src/',
    ],
    'dependency_manifests' => [
        'composer.json' => 'composer.lock',
        'package.json' => 'package-lock.json',
    ],
    'prohibited_prefixes' => [
        '.cursor/',
        '.git/',
        '.github/',
        '.vscode/',
        'agent-transcripts/',
        'audit-output/',
        'backup/',
        'cli/',
        'db/',
        'dbase/',
        'deploy/',
        'docs/',
        'logs/',
        'node_modules/',
        'output/',
        'scripts/',
        'test-results/',
        'tests/',
        'tools/',
        'update/',
        'uploads/',
        'var/',
    ],
    'prohibited_basename_patterns' => [
        '/(^|[._-])(debug|fix|repair|setup|test|tests|example|examples|backup)([._-]|$)/i',
        '/\.(bak|dump|log|patch|sql|sqlite|sqlite3|xls|xlsx)$/i',
        '/(^|\/)\.env($|\.)/i',
        '/(^|\/)(id_rsa|id_ed25519|authorized_keys)(\.|$)/i',
    ],

    // Compatibility keys retained for the Commercial V1 Step 1 gate.
    'allow_directories' => [
        'ajax',
        'api',
        'classes',
        'config',
        'css',
        'dist',
        'do',
        'fonts',
        'images',
        'img',
        'includes',
        'js',
        'lang',
        'PhpSpreadsheet',
        'print',
        'src',
        'vendor',
    ],
    'allow_root_globs' => [
        '.htaccess',
        'Caddyfile',
        'LICENSE',
        'LICENSE.md',
        'composer.json',
        'composer.lock',
        'package.json',
        'package-lock.json',
        'favicon.ico',
        'robots.txt',
        '*.php',
        '*.js',
        '*.css',
        '*.map',
        '*.png',
        '*.jpg',
        '*.jpeg',
        '*.gif',
        '*.svg',
        '*.webp',
        '*.ico',
        '*.woff',
        '*.woff2',
        '*.ttf',
        '*.eot',
    ],
    'deny_path_prefixes' => [
        'tools/',
        'tests/',
        'docs/',
        'cli/',
        'deploy/',
        'backup/',
        'logs/',
        'var/',
        'db/',
        'dbase/',
        'update/',
        'scripts/',
        'output/',
        'uploads/',
        '.git/',
        '.github/',
        '.cursor/',
        'node_modules/',
        'agent-transcripts/',
    ],
    'deny_path_exact' => require __DIR__ . '/prohibited_web_routes.php',
    'deny_name_globs' => [
        'debug_*.php',
        'check_*.php',
        'fix_*.php',
        'repair_*.php',
        'setup_demo*.php',
        'run_*_updates.php',
        'run_migrations.php',
        '*.sql',
        '*.log',
        '*.bak',
        '.env',
        '.env.*',
    ],
];
