<?php

require_once __DIR__ . '/../config/app_config.php';
require_once __DIR__ . '/../classes/Recipe/RecipeFeatureFlags.php';
require_once __DIR__ . '/../classes/Recipe/RecipePilotEvidenceService.php';

if (PHP_SAPI !== 'cli') {
    fwrite(STDERR, "This tool must be run from the command line.\n");
    exit(1);
}

$options = getopt('', [
    'json',
    'help',
    'output:',
    'force',
    'operator::',
    'note::',
    'pos-tenant::',
    'pos-branch::',
    'store-id::',
    'include-all-proofs',
]);

if (isset($options['help'])) {
    recipePilotEvidenceBundleUsage();
    exit(0);
}

$root = dirname(__DIR__);
$flags = new RecipeFeatureFlags(posmain_app_config());
$service = new RecipePilotEvidenceService();

try {
    $result = recipePilotEvidenceBundleBuild($root, $service, $flags, $options);
} catch (Throwable $exception) {
    $result = [
        'ok' => false,
        'error' => get_class($exception),
        'message' => $exception->getMessage(),
    ];
}

if (isset($options['json'])) {
    echo json_encode($result, JSON_PRETTY_PRINT | JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) . PHP_EOL;
} else {
    recipePilotEvidenceBundlePrintHuman($result);
}

exit(!empty($result['ok']) ? 0 : 2);

function recipePilotEvidenceBundleUsage(): void
{
    fwrite(STDOUT, "Usage: php tools/recipe_pilot_evidence_bundle.php [--json] [--output=/absolute/path.md] [--force] [--include-all-proofs] [--pos-tenant=0] [--pos-branch=0] [--store-id=0] [--operator=name] [--note=text]\n");
    fwrite(STDOUT, "\n");
    fwrite(STDOUT, "Builds a draft-only recipe pilot evidence file from read-only/runtime-proof commands.\n");
    fwrite(STDOUT, "The generated bundle is not valid for rollout by itself: pass markers, completed-at, browser/operator details, and checklist items remain pending.\n");
    fwrite(STDOUT, "It runs only fixed local commands: recipe runtime preflight, pilot fixture verify, rollout readiness, and the isolated runtime proof suite.\n");
    fwrite(STDOUT, "It does not apply migrations, change feature flags, log in, submit browser forms, create customer orders, write recipe rows, write stock, post accounting, or enqueue sync.\n");
    fwrite(STDOUT, "Browser/operator action details and checklist items remain pending for the operator to complete manually.\n");
}

function recipePilotEvidenceBundleBuild(string $root, RecipePilotEvidenceService $service, RecipeFeatureFlags $flags, array $options): array
{
    $scope = recipePilotEvidenceBundleScope($flags, $options);
    $commands = recipePilotEvidenceBundleCommands(!empty($options['include-all-proofs']), $scope);
    $commandResults = [];
    foreach ($commands as $key => $command) {
        $commandResults[$key] = recipePilotEvidenceBundleRun($root, $command);
    }
    $content = $service->template($flags, [
        'pos_tenant' => array_key_exists('pos_tenant', $scope) ? (string) $scope['pos_tenant'] : '',
        'pos_branch' => array_key_exists('pos_branch', $scope) ? (string) $scope['pos_branch'] : '',
        'store_id' => array_key_exists('store_id', $scope) ? (string) $scope['store_id'] : '',
        'operator' => $options['operator'] ?? '',
        'note' => trim((string) (($options['note'] ?? '') . ' Draft generated by tools/recipe_pilot_evidence_bundle.php; browser/operator action lines are intentionally pending.')),
    ]);

    $replacements = recipePilotEvidenceBundleEvidenceReplacements($commandResults);
    foreach ($replacements as $label => $value) {
        $content = preg_replace(
            '/^-\s*' . preg_quote($label, '/') . '\s*:\s*pending\s*$/m',
            '- ' . $label . ': ' . $value,
            $content
        ) ?? $content;
    }

    $proofLines = recipePilotEvidenceBundleProofLines($commandResults['runtime_proof_suite']['payload'] ?? []);
    foreach ($proofLines as $label => $line) {
        $content = preg_replace(
            '/^-\s*' . preg_quote($label, '/') . '\s*:\s*pending\s*\(run:\s*php\s*[^)]*\)\s*$/m',
            '- ' . $label . ': ' . $line,
            $content
        ) ?? $content;
    }

    $output = trim((string) ($options['output'] ?? ''));
    $written = false;
    if ($output !== '') {
        if (is_file($output) && !array_key_exists('force', $options)) {
            throw new RuntimeException('Output file already exists. Pass --force to overwrite it.');
        }
        $dir = dirname($output);
        if (!is_dir($dir) || !is_writable($dir)) {
            throw new RuntimeException('Output directory is not writable: ' . $dir);
        }
        if (file_put_contents($output, $content . PHP_EOL) === false) {
            throw new RuntimeException('Unable to write evidence bundle output.');
        }
        $written = true;
    }

    $blockers = [];
    foreach ($commandResults as $key => $commandResult) {
        if (!recipePilotEvidenceBundleCommandAcceptable((string) $key, $commandResult)) {
            $blockers[] = 'recipe_pilot_evidence_bundle_' . $key . '_failed';
        }
    }

    return [
        'ok' => $blockers === [],
        'draft_only' => true,
        'valid_for_rollout' => false,
        'operator_action_required' => true,
        'checked_at_utc' => gmdate('Y-m-d\TH:i:s\Z'),
        'mode' => $flags->mode(),
        'required_scope' => $scope,
        'read_only' => true,
        'written' => $written,
        'path' => $written ? $output : null,
        'content' => $written ? null : $content,
        'commands' => $commandResults,
        'pending_operator_items' => recipePilotEvidenceBundlePendingOperatorItems($service, $flags),
        'blockers' => $blockers,
        'warnings' => ['recipe_pilot_evidence_bundle_operator_items_pending'],
    ];
}

function recipePilotEvidenceBundleCommands(bool $includeAllProofs, array $scope): array
{
    $scopeArgs = recipePilotEvidenceBundleScopeArgs($scope);

    return [
        'runtime_preflight' => ['tools/recipe_runtime_preflight.php', '--json'],
        'pilot_fixture_verify' => array_merge(['tools/recipe_pilot_fixture.php', '--verify', '--json'], $scopeArgs),
        'rollout_readiness' => array_merge(['tools/recipe_rollout_readiness.php', '--json'], $scopeArgs),
        'runtime_proof_suite' => $includeAllProofs
            ? ['tools/recipe_runtime_proof_suite.php', '--all', '--json']
            : ['tools/recipe_runtime_proof_suite.php', '--json'],
    ];
}

function recipePilotEvidenceBundleScopeArgs(array $scope): array
{
    $args = [];
    foreach ([
        'pos_tenant' => '--pos-tenant=',
        'pos_branch' => '--pos-branch=',
        'store_id' => '--store-id=',
    ] as $key => $prefix) {
        if (array_key_exists($key, $scope)) {
            $args[] = $prefix . (int) $scope[$key];
        }
    }

    return $args;
}

function recipePilotEvidenceBundleRun(string $root, array $args): array
{
    $command = array_merge([PHP_BINARY], $args);
    $process = proc_open($command, [
        0 => ['pipe', 'r'],
        1 => ['pipe', 'w'],
        2 => ['pipe', 'w'],
    ], $pipes, $root, null);
    if (!is_resource($process)) {
        return [
            'ok' => false,
            'command' => recipePilotEvidenceBundleCommandString($args),
            'error' => 'process_start_failed',
        ];
    }

    fclose($pipes[0]);
    $stdout = stream_get_contents($pipes[1]);
    $stderr = stream_get_contents($pipes[2]);
    fclose($pipes[1]);
    fclose($pipes[2]);
    $exitCode = proc_close($process);
    $stdout = is_string($stdout) ? trim($stdout) : '';
    $stderr = is_string($stderr) ? trim($stderr) : '';
    $payload = json_decode($stdout, true);
    $payload = is_array($payload) ? $payload : null;

    return [
        'ok' => $exitCode === 0 && is_array($payload) && !empty($payload['ok']),
        'command' => recipePilotEvidenceBundleCommandString($args),
        'exit_code' => $exitCode,
        'payload' => $payload,
        'stdout' => $stdout,
        'stderr' => $stderr,
    ];
}

function recipePilotEvidenceBundleCommandString(array $args): string
{
    return 'php ' . implode(' ', array_map('strval', $args));
}

function recipePilotEvidenceBundleCommandAcceptable(string $key, array $result): bool
{
    if (!empty($result['ok'])) {
        return true;
    }
    if ($key !== 'rollout_readiness') {
        return false;
    }

    $payload = $result['payload'] ?? null;
    if (!is_array($payload)) {
        return false;
    }

    $blockers = array_values(array_map('strval', (array) ($payload['blockers'] ?? [])));
    sort($blockers);
    if ($blockers !== ['recipe_pilot_evidence_file_not_provided']) {
        return false;
    }

    foreach (['schema', 'configuration', 'runtime_preflight', 'dashboard'] as $checkKey) {
        if (empty($payload['checks'][$checkKey]['ok'])) {
            return false;
        }
    }

    return true;
}

function recipePilotEvidenceBundleEvidenceReplacements(array $results): array
{
    $preflight = $results['runtime_preflight']['payload'] ?? [];
    $fixture = $results['pilot_fixture_verify']['payload'] ?? [];
    $readiness = $results['rollout_readiness']['payload'] ?? [];

    $schemaPending = (int) ($preflight['checks']['schema']['pending_count'] ?? -1);
    $issueTotal = (int) ($readiness['dashboard_summary']['issue_total'] ?? -1);
    $fixtureReady = !empty($fixture['fixture_ready_for_operator_qa']) ? 'true' : 'false';

    return [
        'Recipe schema evidence' => 'tools/run_migrations.php --dry-run equivalent via tools/recipe_runtime_preflight.php --json pending_count=' . $schemaPending,
        'Recipe runtime preflight evidence' => 'tools/recipe_runtime_preflight.php --json ready_for_recipe_operator_qa=' . (!empty($preflight['ready_for_recipe_operator_qa']) ? 'true' : 'false'),
        'Pilot fixture verification evidence' => 'tools/recipe_pilot_fixture.php --verify --json fixture_ready_for_operator_qa=' . $fixtureReady,
        'Recipe operational dashboard evidence' => 'recipe_operational_dashboard.php issue_total=' . $issueTotal . ' via tools/recipe_rollout_readiness.php --json',
        'Recipe rollback evidence' => 'POSMAIN_RECIPE_MODE=off rollback documented; disable recipe write flags to return to legacy behavior.',
    ];
}

function recipePilotEvidenceBundleProofLines(array $proofSuite): array
{
    $lines = [];
    foreach (($proofSuite['results'] ?? []) as $label => $result) {
        if (!is_array($result) || empty($result['ok']) || empty($result['evidence_line'])) {
            continue;
        }
        $label = (string) $label;
        $line = (string) $result['evidence_line'];
        $prefix = $label . ': ';
        if (strpos($line, $prefix) === 0) {
            $line = substr($line, strlen($prefix));
        }
        $lines[$label] = $line;
    }

    return $lines;
}

function recipePilotEvidenceBundlePendingOperatorItems(RecipePilotEvidenceService $service, RecipeFeatureFlags $flags): array
{
    return [
        'details' => array_values(array_diff($service->requiredDetails($flags), array_keys(recipePilotEvidenceBundleEvidenceReplacements([])))),
        'checks' => $service->requiredChecks($flags),
    ];
}

function recipePilotEvidenceBundleScope(RecipeFeatureFlags $flags, array $options): array
{
    $scope = [];
    foreach ([
        'pos-tenant' => 'pos_tenant',
        'pos-branch' => 'pos_branch',
        'store-id' => 'store_id',
    ] as $option => $key) {
        if (array_key_exists($option, $options) && $options[$option] !== '' && $options[$option] !== null && (int) $options[$option] >= 0) {
            $scope[$key] = (int) $options[$option];
        }
    }

    $appBranch = $flags->appConfig()['branch'] ?? [];
    if (!array_key_exists('pos_tenant', $scope)
        && is_array($appBranch)
        && array_key_exists('pos_tenant', $appBranch)
        && $appBranch['pos_tenant'] !== null
        && $appBranch['pos_tenant'] !== ''
        && (int) $appBranch['pos_tenant'] >= 0
    ) {
        $scope['pos_tenant'] = (int) $appBranch['pos_tenant'];
    }
    if (!array_key_exists('pos_branch', $scope)) {
        $pilotBranch = trim((string) (($flags->config()['pilot'] ?? [])['pos_branch'] ?? ''));
        if ($pilotBranch !== '' && (int) $pilotBranch >= 0) {
            $scope['pos_branch'] = (int) $pilotBranch;
        }
    }
    if (!array_key_exists('pos_branch', $scope)
        && is_array($appBranch)
        && array_key_exists('pos_branch', $appBranch)
        && $appBranch['pos_branch'] !== null
        && $appBranch['pos_branch'] !== ''
        && (int) $appBranch['pos_branch'] >= 0
    ) {
        $scope['pos_branch'] = (int) $appBranch['pos_branch'];
    }

    return $scope;
}

function recipePilotEvidenceBundlePrintHuman(array $result): void
{
    fwrite(STDOUT, 'Recipe pilot evidence bundle: ' . (!empty($result['ok']) ? 'DRAFT OK' : 'DRAFT FAILED') . PHP_EOL);
    fwrite(STDOUT, '- draft_only: true' . PHP_EOL);
    fwrite(STDOUT, '- valid_for_rollout: false' . PHP_EOL);
    fwrite(STDOUT, '- operator_action_required: true' . PHP_EOL);
    if (!empty($result['path'])) {
        fwrite(STDOUT, '- path: ' . (string) $result['path'] . PHP_EOL);
    }
    if (!empty($result['blockers']) && is_array($result['blockers'])) {
        fwrite(STDOUT, "- blockers:\n");
        foreach ($result['blockers'] as $blocker) {
            fwrite(STDOUT, '  - ' . (string) $blocker . PHP_EOL);
        }
    }
    if (array_key_exists('content', $result) && is_string($result['content'])) {
        fwrite(STDOUT, PHP_EOL . (string) $result['content'] . PHP_EOL);
    }
}
